name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev \
          libgtest-dev cmake build-essential
        # Build and install Google Test
        cd /usr/src/gtest && sudo cmake . && sudo make && sudo cp lib/*.a /usr/lib
    - name: Run tests
      working-directory: ./test
      run: make test
